# See https://mise.jdx.dev/configuration/settings.html.

[settings]
cache_prune_age = '7d'
disable_backends = ['asdf']
minimum_release_age = '3d'
paranoid = true

[tools]
maven = '3.9'
node = '24'
ruby = '3.4'

java.shorthand_vendor = 'temurin'
