# See https://mise.jdx.dev/configuration/settings.html.

[settings]
cache_prune_age = '7d'
disable_backends = ['asdf']
java.shorthand_vendor = 'temurin'
minimum_release_age = '3d'
paranoid = true
ruby.compile = false

[tools]
maven = 'latest'
node = 'latest'
opencode = 'latest'
ruby = 'latest'
usage = 'latest'
